language: php

php:
  - 7.4

services:
  - mysql

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - composer install
  - php artisan migrate

script:
  - composer lint
  - composer test:coverage
  - php ./coverage-checker.php build/logs/clover.xml 38

after_success:
  - travis_retry  vendor/bin/php-coveralls -v
